// Mirrors daemon/internal/pifi/model.go. Units are the human-facing ones --
// megabits, milliseconds, percent -- and are converted to the kernel's
// bits/seconds/fractions in exactly one place on the server.

export interface Shape {
  rate_mbps: number;
  delay_ms: number;
  jitter_ms: number;
  loss_pct: number;
  reorder_pct: number;
  corrupt_pct: number;
}

/**
 * The impairments kept out of the way until they are used.
 *
 * netem's `duplicate` is absent on purpose. It cannot coexist with any other
 * netem qdisc on the same interface, in either order, so one device using it
 * would make every other device on that port unconditionable -- see the note in
 * the daemon's Shape.
 *
 * Not a preference and not a menu: which controls are on screen is derived from
 * whether they are doing anything. A device with none of these set shows four
 * sliders; set one and it stays visible for as long as it is in force. So the
 * page is quiet by default and nothing conditioning the traffic can ever be
 * hidden — the failure a "show these controls" checkbox list would invite.
 *
 * They are second-tier because the traffic here rarely needs them, not because
 * they are lesser: rate and delay are what this box is for, loss and jitter are
 * the common companions, and these three are the long tail.
 */
export const EXTRA_IMPAIRMENTS = [
  {
    key: 'reorder_pct' as const,
    label: 'reorder',
    unit: '%',
    max: 50,
    step: 0.5,
    /** netem cannot reorder without a delay queue to skip. */
    needsDelay: true,
    title: 'Packets released ahead of the delay queue, arriving out of order. TCP treats this very differently from loss.',
  },
  {
    key: 'corrupt_pct' as const,
    label: 'corrupt',
    unit: '%',
    max: 20,
    step: 0.1,
    needsDelay: false,
    title: 'Packets given a bit error. The receiver discards them on checksum, so the link is consumed but nothing arrives — unlike loss, where nothing is sent.',
  },
];

/** Whether any second-tier impairment is in force in this shape. */
export function hasExtras(s: Shape): boolean {
  return EXTRA_IMPAIRMENTS.some((e) => (s[e.key] ?? 0) > 0);
}

export interface Match {
  dst_port?: number;
  dst_cidr?: string;
  protocol?: string;
}

export interface SubClass {
  id: string;
  name: string;
  match: Match;
  down: Shape;
  up: Shape;
  enabled: boolean;
}

export interface Rung {
  /** What the rendition costs on the wire. */
  mbps: number;
  /**
   * The caps at which the client climbed INTO this rendition and fell OUT of
   * it. Both matter, because the cost alone cannot drive a pattern: a player
   * wants headroom, so capping at a rung's own bitrate does not hold it there.
   * They differ from each other because ABR players use hysteresis on purpose.
   * Absent when not observed in this run's direction.
   */
  up_at_mbps?: number;
  down_at_mbps?: number;
  /** The window behind this rung drifted: its two halves disagreed. */
  unstable?: boolean;
}

/**
 * One service's rendition ladder as seen by one device.
 *
 * Keyed by service, never by device alone: the same box streaming Netflix and
 * YouTube produces two ladders with nothing in common, so storing one per
 * device would have each sweep silently overwrite the last.
 */
export interface Ladder {
  service: string;
  rungs: Rung[];
  /** 'typed' | 'fetched' | 'measured' | 'inferred' -- rendered differently,
   *  because they are different strengths of claim. */
  provenance: string;
  measured_at?: number;
  note?: string;
}

/**
 * How a segment arrives at its closing keyframe.
 *
 * Both are real links: a handover or a lift door is a step, walking out of
 * range is a ramp. A timeline that could only express one of them would be
 * describing half of what happens on a radio.
 */
export type Ease = 'hold' | 'ramp';

/** The whole conditioning policy at one instant on a pattern's timeline. */
export interface Keyframe {
  /** Offset from the start, on half-second boundaries. */
  at_sec: number;
  down: Shape;
  up: Shape;
  /** How the run gets HERE from the keyframe before it. Meaningless on the first. */
  ease?: Ease;
}

/**
 * A timeline of keyframes.
 *
 * There is no wrap mode: a loop restarts at the first keyframe, so a pattern
 * that loops smoothly is one whose last keyframe holds the same values as its
 * first — visible on the timeline, unlike a flag whose effect only shows up
 * during playback.
 */
export interface Pattern {
  name: string;
  keys: Keyframe[];
  loop: boolean;
}

/**
 * One row of the pattern library.
 *
 * Built-ins are GENERATED by the daemon from the device's ladder on every
 * request, so a row's rates and duration describe the ladder as it is now.
 * That is why the list is fetched rather than held in the client: a
 * hard-coded "valley" would be a guess at rates the box has measured.
 */
export interface PatternEntry {
  name: string;
  builtin: boolean;
  dur_sec: number;
  keys: number;
  loop: boolean;
  selected?: boolean;
  /** Which ladder a built-in was generated from, and how strong a claim it is.
   *  'default' means the stand-in ladder, so the shape is plausible rather
   *  than measured -- a difference the operator must be able to see. */
  ladder_service?: string;
  ladder?: string;
  /** Why this row cannot be built right now, e.g. a stretch that runs past
   *  what the engine will play. Shown rather than hidden: a row that silently
   *  vanishes reads as a missing feature. */
  unavailable?: string;
}

/**
 * Live progress of a pattern run.
 *
 * Distinct from `Policy.pattern`, which is the timeline as authored: this is a
 * playhead moving along it, and only one of the two is editable.
 */
export interface PatternView {
  state: 'running' | 'paused' | 'done';
  name: string;
  pos_sec: number;
  dur_sec: number;
  loop: boolean;
  laps: number;
  /** The keyframe currently in force — the one last passed, not the next. */
  index: number;
  /** What is ENFORCED now, which during a ramp equals no keyframe. */
  down: Shape;
  up: Shape;
  reason?: string;
  started_at: number;
}

export interface Policy {
  mac: string;
  rev: number;
  label: string;
  enabled: boolean;
  down: Shape;
  up: Shape;
  sub: SubClass[] | null;
  ladders?: Ladder[] | null;
  pattern?: Pattern | null;
}

export interface SweepLevel {
  level: number;
  cap_mbps: number;
  rate_mbps: number;
  drift: number;
  saturated: boolean;
  new_rung: boolean;
  samples: number;
}

/** Live progress of a ladder sweep. Absent unless one has run this session. */
export interface SweepView {
  state: 'running' | 'done' | 'failed';
  phase: string;
  service: string;
  level: number;
  cap_mbps: number;
  ceiling_mbps: number;
  found?: Rung[];
  levels?: SweepLevel[];
  reason?: string;
  started_at: number;
}

export interface Station {
  mac: string;
  signal_dbm: number;
  tx_bytes: number;
  rx_bytes: number;
  tx_phy_mbps: number;
  rx_phy_mbps: number;
  tx_failed: number;
  connected_sec: number;
  inactive_ms: number;
}

export interface Counters {
  bytes: number;
  packets: number;
  drops: number;
  overlimits: number;
  backlog: number;
  qlen: number;
  throughput_mbps: number;
  cap_mbps: number;
}

export interface Client {
  mac: string;
  ip?: string;
  /** Routable IPv6 addresses; a device usually holds several at once. */
  ipv6?: string[];
  hostname?: string;
  label: string;
  medium: string;
  port?: string;
  present: boolean;
  shapeable: boolean;
  station?: Station;
  policy: Policy;
  last_seen: number;
  down_counters: Counters;
  up_counters: Counters;
  sub_counters?: Record<string, Counters>;
  sweep?: SweepView;
  pattern_run?: PatternView;
}

export interface Capabilities {
  shaping: boolean;
  uplink: boolean;
  radio: boolean;
  leases: boolean;
  wlan_iface: string;
  uplink_if: string;
  /** True only when ntopng is ANSWERING, not merely installed. */
  ntopng: boolean;
  ntopng_port: number;
  /** True only when the iperf3 server is LISTENING, not merely installed. */
  iperf: boolean;
  iperf_port: number;
  reason?: string;
}

/**
 * Build a deep link into ntopng.
 *
 * The host comes from the current page rather than being hardcoded, so links
 * work however you reached it -- infinite-streaming-pifi.local, its DHCP address, or the rescue
 * address. Only the port is fixed.
 *
 * ifid=0 is br-lan: ntopng watches the bridge, the one interface that sees
 * every client on both media in both directions.
 */
export function ntopngUrl(
  port: number,
  path = '',
  params: Record<string, string> = {},
): string {
  const host = window.location.hostname || 'localhost';
  if (!path) return `http://${host}:${port}/`;
  const qs = new URLSearchParams({ ifid: '0', ...params }).toString();
  return `http://${host}:${port}${path}?${qs}`;
}

export interface Notice {
  /** "error" sits at the top of the page; "info" is a footnote at the bottom. */
  level: 'error' | 'info';
  text: string;
}

export interface Snapshot {
  revision: number;
  control_revision: number;
  time: number;
  caps: Capabilities;
  clients: Client[];
  notices?: Notice[];
}

export const CLEAN: Shape = {
  rate_mbps: 0,
  delay_ms: 0,
  jitter_ms: 0,
  loss_pct: 0,
  reorder_pct: 0,
  corrupt_pct: 0,
};

// Named starting points. These are approximations of real-world links, not
// standards -- the numbers come from typical measured behaviour and are meant
// as a place to start rather than a certification profile.
export interface Preset {
  name: string;
  note: string;
  down: Shape;
  up: Shape;
}

export const PRESETS: Preset[] = [
  { name: 'Clean', note: 'no conditioning', down: { ...CLEAN }, up: { ...CLEAN } },
  {
    name: 'Fibre',
    note: '100 Mbps, 8 ms',
    down: { ...CLEAN, rate_mbps: 100, delay_ms: 4, jitter_ms: 1, loss_pct: 0 },
    up: { ...CLEAN, rate_mbps: 40, delay_ms: 4, jitter_ms: 1, loss_pct: 0 },
  },
  {
    name: 'Cable',
    note: '30 Mbps, 30 ms',
    down: { ...CLEAN, rate_mbps: 30, delay_ms: 15, jitter_ms: 4, loss_pct: 0.05 },
    up: { ...CLEAN, rate_mbps: 6, delay_ms: 15, jitter_ms: 4, loss_pct: 0.05 },
  },
  {
    name: '4G good',
    note: '20 Mbps, 50 ms',
    down: { ...CLEAN, rate_mbps: 20, delay_ms: 25, jitter_ms: 8, loss_pct: 0.1 },
    up: { ...CLEAN, rate_mbps: 8, delay_ms: 25, jitter_ms: 8, loss_pct: 0.1 },
  },
  {
    name: '4G weak',
    note: '3 Mbps, 120 ms, 1%',
    down: { ...CLEAN, rate_mbps: 3, delay_ms: 60, jitter_ms: 25, loss_pct: 1 },
    up: { ...CLEAN, rate_mbps: 1, delay_ms: 60, jitter_ms: 25, loss_pct: 1 },
  },
  {
    name: '3G',
    note: '1.5 Mbps, 200 ms, 1.5%',
    down: { ...CLEAN, rate_mbps: 1.5, delay_ms: 100, jitter_ms: 40, loss_pct: 1.5 },
    up: { ...CLEAN, rate_mbps: 0.5, delay_ms: 100, jitter_ms: 40, loss_pct: 1.5 },
  },
  {
    name: 'Satellite',
    note: '25 Mbps, 600 ms',
    down: { ...CLEAN, rate_mbps: 25, delay_ms: 300, jitter_ms: 20, loss_pct: 0.2 },
    up: { ...CLEAN, rate_mbps: 3, delay_ms: 300, jitter_ms: 20, loss_pct: 0.2 },
  },
  {
    name: 'Lossy',
    note: '10 Mbps, 5% loss',
    down: { ...CLEAN, rate_mbps: 10, delay_ms: 20, jitter_ms: 10, loss_pct: 5 },
    up: { ...CLEAN, rate_mbps: 5, delay_ms: 20, jitter_ms: 10, loss_pct: 5 },
  },
];

/**
 * Throughput history for one client, in Mbps.
 *
 * Parallel arrays sharing an index rather than an array of objects: at 3600
 * points per client per direction this is the difference between three arrays
 * and 3600 short-lived objects rebuilt on every tick.
 *
 * `t` carries the wall-clock time of each sample. The x-axis was formerly an
 * implied 1 Hz sequence, which cannot represent either of the two things that
 * now happen routinely: a long range arriving pre-averaged into wider buckets,
 * and a gap where the daemon restarted or the device went away. Without real
 * timestamps both are silently squeezed into a continuous line and the chart
 * misreports when things happened.
 */
export interface Series {
  t: number[];
  down: number[];
  up: number[];
  /**
   * The downlink cap in force at each sample, 0 for unlimited.
   *
   * Parallel to `t`, because a pattern moves the cap while the chart is being
   * watched: the device's current cap says nothing about what was enforced when
   * the player reacted three minutes ago, and lining those two up is the whole
   * point of the box.
   */
  cap: number[];
}

/** Chart time ranges, in the `{ v, label }` shape the streaming dashboard uses. */
export const RANGES = [
  { v: 60, label: '1m' },
  { v: 300, label: '5m' },
  { v: 900, label: '15m' },
  { v: 3600, label: '1h' },
] as const;

/**
 * How the y-axis maximum is chosen.
 *
 * - `auto`   — follow the data (and the cap), rescaling as traffic changes.
 * - `cap`    — lock to the configured cap, so the headroom between what a
 *              device is doing and what it is allowed to do stays a constant
 *              distance. That gap is the question these charts exist to answer,
 *              and an axis that rescales hides it.
 * - `manual` — a fixed ceiling, so two devices an order of magnitude apart can
 *              be compared on one scale instead of both filling their panes.
 *
 * Linear throughout, deliberately: zero is a real and frequent value here (a
 * player that has filled its buffer stops requesting), and a log axis has no
 * position for it. See the note in TrafficChart.
 */
export type YMode = 'auto' | 'cap' | 'manual';

/**
 * Window for the sustained line, in seconds.
 *
 * An adaptive player does not consume bandwidth per second: it pulls a segment
 * at whatever rate it can get, then idles while the buffer drains. The live
 * trace is therefore a square wave between roughly the cap and zero, and
 * neither extreme answers "what is this device actually getting".
 *
 * 30s spans five fetch cycles at the 6s segment duration that is the common
 * case, and fifteen at a 2s cadence -- enough for the line to sit still rather
 * than breathe with each fetch. The cost is a trailing lag of half the window,
 * so a cap change takes ~15s to be fully reflected.
 */
export const SUSTAINED_SEC = 30;

/*
 * The rate scale, shared by the slider and the pattern timeline.
 *
 * A linear 0-200 Mbps control puts every interesting mobile-network rate --
 * 0.5 to 5 Mbps -- inside the first three pixels of travel, which makes the
 * most-used part of the range unusable. Position 0 is reserved for
 * "unlimited", which has no place on a log scale at all.
 *
 * The timeline plots its curve on the same scale for the same reason, and so
 * that a ramp authored as a straight line on the slider draws as a straight
 * line on the chart.
 */
export const RATE_MIN = 0.1;
export const RATE_MAX = 200;

export function posToRate(p: number): number {
  if (p <= 0) return 0;
  const r = RATE_MIN * Math.pow(RATE_MAX / RATE_MIN, (p - 1) / 99);
  return r < 1 ? Math.round(r * 100) / 100 : Math.round(r * 10) / 10;
}

export function rateToPos(r: number): number {
  if (r <= 0) return 0;
  return Math.round(1 + (99 * Math.log(r / RATE_MIN)) / Math.log(RATE_MAX / RATE_MIN));
}

/**
 * Starting timelines.
 *
 * Absolute Mbps, deliberately: pifi cannot read a manifest, so it does not know
 * where this device's renditions sit. A step at "4 Mbps" says a player got
 * 4 Mbps; a step at "just above rung 3" would say which rendition it should
 * have sustained, which is the better question — and the one #28 exists to
 * answer by generating these from a measured ladder instead.
 *
 * Every keyframe time lands on a whole second. Throughput is sampled once a
 * second, so a transition finer than that could be configured but never
 * observed.
 */
export interface PatternTemplate {
  name: string;
  note: string;
  make: () => Pattern;
}

const clean = (): Shape => ({ ...CLEAN });
const at = (
  at_sec: number,
  down: Partial<Shape>,
  ease: Ease = 'hold',
): Keyframe => ({
  at_sec,
  down: { ...CLEAN, ...down },
  up: { ...CLEAN, ...down, rate_mbps: 0 },
  ease,
});

/**
 * Starting points for AUTHORING a timeline by hand.
 *
 * Deliberately not the same thing as the pattern library. These are impairment
 * scenarios -- a tunnel, a handover -- whose rates are illustrative and are
 * meant to be dragged around. The library's valley and pyramid are generated by
 * the daemon from the device's measured ladder and describe real renditions.
 *
 * A hard-coded "valley" used to live here at 12 and 1.5 Mbps. It was removed
 * when the ladder-derived one arrived: two different patterns under one name,
 * one of them invented, is worse than either.
 */
export const PATTERN_TEMPLATES: PatternTemplate[] = [
  {
    name: 'tunnel',
    note: 'clean, then the link all but disappears for 15s, then clean',
    make: () => ({
      name: 'tunnel',
      loop: true,
      keys: [
        at(0, { ...CLEAN, rate_mbps: 25 }),
        at(30, { ...CLEAN, rate_mbps: 25 }),
        at(31, { ...CLEAN, rate_mbps: 0.2, delay_ms: 400, jitter_ms: 200, loss_pct: 15 }),
        at(46, { ...CLEAN, rate_mbps: 0.2, delay_ms: 400, jitter_ms: 200, loss_pct: 15 }),
        at(47, { ...CLEAN, rate_mbps: 25 }),
        at(70, { ...CLEAN, rate_mbps: 25 }),
      ],
    }),
  },
  {
    name: 'congested cell',
    note: 'a sawtooth: capacity bleeds away, then the cell empties',
    make: () => ({
      name: 'congested cell',
      loop: true,
      keys: [
        at(0, { ...CLEAN, rate_mbps: 20, delay_ms: 30, jitter_ms: 10 }),
        at(45, { ...CLEAN, rate_mbps: 2, delay_ms: 120, jitter_ms: 60, loss_pct: 1 }),
        at(46, { ...CLEAN, rate_mbps: 20, delay_ms: 30, jitter_ms: 10 }),
      ],
    }),
  },
  {
    name: 'handover',
    note: 'a clean step between two cells, with a latency spike across it',
    make: () => ({
      name: 'handover',
      loop: true,
      keys: [
        at(0, { ...CLEAN, rate_mbps: 15, delay_ms: 30, jitter_ms: 5 }),
        at(25, { ...CLEAN, rate_mbps: 15, delay_ms: 30, jitter_ms: 5 }),
        at(26, { ...CLEAN, rate_mbps: 0.5, delay_ms: 600, jitter_ms: 300, loss_pct: 5 }),
        at(29, { ...CLEAN, rate_mbps: 6, delay_ms: 80, jitter_ms: 20 }),
        at(55, { ...CLEAN, rate_mbps: 6, delay_ms: 80, jitter_ms: 20 }),
      ],
    }),
  },
];

/** A first pattern for a device with none: its current policy, held, twice. */
export function patternFromPolicy(down: Shape, up: Shape): Pattern {
  return {
    name: 'pattern',
    loop: true,
    keys: [
      { at_sec: 0, down: { ...down }, up: { ...up } },
      { at_sec: 30, down: { ...down }, up: { ...up }, ease: 'hold' },
    ],
  };
}

export interface ChartPrefs {
  rangeSec: number;
  yMode: YMode;
  /** Ceiling in Mbps for `manual`; ignored in the other modes. */
  yManual: number;
  /** Draw the per-sample trace. */
  showLive: boolean;
  /** Draw the rolling mean over SUSTAINED_SEC. */
  showSustained: boolean;
}
