package boa

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"
	"time"
)

// docs/API.md is generated from this package's source and checked in. This test
// regenerates it and fails if the committed copy differs, which is the whole
// point: a reference that has to be regenerated by hand goes stale silently and
// then lies confidently. (Measured in the sibling `smashing` repo on
// 2026-09-07: its generated swagger.yaml was last rebuilt 2026-05-27 while the
// annotations it derives from were edited 2026-07-09, so the published API docs
// described a contract six weeks out of date and nothing reported it.)
//
// Here the doc cannot drift from the code, because the code IS the doc: routes
// come from the mux registrations in api.go, prose comes verbatim from the Go
// doc comments already written on the handlers and the wire types, and the
// field lists come from the same wireRoots table the drift test uses.
//
//	go test ./internal/boa/ -run TestAPIDocs -update
//
// Nothing generated is committed except the Markdown, and no tool beyond the
// standard library is involved -- the daemon's go.mod stays empty.

var updateDocs = flag.Bool("update", false, "rewrite docs/API.md from the source")

const apiDocPath = "../../../docs/API.md"

func TestAPIDocsUpToDate(t *testing.T) {
	pkg, err := parsePackageDocs(".")
	if err != nil {
		t.Fatalf("parsing package source: %v", err)
	}
	want, err := renderAPIDocs(pkg)
	if err != nil {
		t.Fatalf("rendering: %v", err)
	}

	if *updateDocs {
		if err := os.WriteFile(filepath.FromSlash(apiDocPath), []byte(want), 0o644); err != nil {
			t.Fatalf("writing %s: %v", apiDocPath, err)
		}
		t.Logf("wrote %s (%d bytes)", apiDocPath, len(want))
		return
	}

	got, err := os.ReadFile(filepath.FromSlash(apiDocPath))
	if err != nil {
		t.Fatalf("reading %s: %v\n\nGenerate it with:\n\tgo test ./internal/boa/ -run TestAPIDocs -update", apiDocPath, err)
	}
	if string(got) == want {
		return
	}
	t.Errorf("%s is out of date with the source.\n\nRegenerate it with:\n"+
		"\tgo test ./internal/boa/ -run TestAPIDocs -update\n\n%s",
		apiDocPath, firstDifference(string(got), want))
}

// firstDifference reports the first line that differs, which is far more use in
// a failure than a diff of a document this size.
func firstDifference(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) && i < len(w); i++ {
		if g[i] != w[i] {
			return fmt.Sprintf("first difference at line %d:\n  committed: %q\n  from source: %q", i+1, g[i], w[i])
		}
	}
	return fmt.Sprintf("committed file has %d lines, source produces %d", len(g), len(w))
}

// --- source model -----------------------------------------------------------

type routeDoc struct {
	Method, Path, Handler string
}

type fieldDoc struct {
	GoName, JSONName, GoType, Doc string
	Omitempty                     bool
}

type typeDoc struct {
	Name, Doc string
	Fields    []fieldDoc
}

type packageDocs struct {
	Routes      []routeDoc
	HandlerDocs map[string]string
	Types       map[string]typeDoc
}

// parsePackageDocs reads the package's own source for the things reflect cannot
// see: the route registrations, and every doc comment.
func parsePackageDocs(dir string) (*packageDocs, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	pkg := &packageDocs{HandlerDocs: map[string]string{}, Types: map[string]typeDoc{}}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		collectFile(f, pkg)
	}
	if len(pkg.Routes) == 0 {
		// No routes means the registration shape changed and this reader is
		// silently finding nothing -- exactly the failure it exists to prevent.
		return nil, fmt.Errorf("no routes found in %s: has Routes() changed shape?", dir)
	}
	return pkg, nil
}

func collectFile(f *ast.File, pkg *packageDocs) {
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Recv != nil && d.Doc != nil {
				pkg.HandlerDocs[d.Name.Name] = cleanDoc(d.Doc.Text())
			}
			if d.Name.Name == "Routes" {
				pkg.Routes = append(pkg.Routes, collectRoutes(d)...)
			}
		case *ast.GenDecl:
			if d.Tok != token.TYPE {
				continue
			}
			for _, spec := range d.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				// A single-spec GenDecl carries the doc on the decl, a grouped
				// one on the spec. Both shapes appear in this package.
				doc := ts.Doc
				if doc == nil {
					doc = d.Doc
				}
				td := typeDoc{Name: ts.Name.Name}
				if doc != nil {
					td.Doc = cleanDoc(doc.Text())
				}
				td.Fields = collectFields(st)
				pkg.Types[ts.Name.Name] = td
			}
		}
	}
}

// collectRoutes pulls `mux.HandleFunc("GET /api/state", a.getState)` out of
// Routes(). Anything not matching that shape is skipped rather than guessed at.
func collectRoutes(fn *ast.FuncDecl) []routeDoc {
	var out []routeDoc
	ast.Inspect(fn, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || len(call.Args) != 2 {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "HandleFunc" {
			return true
		}
		lit, ok := call.Args[0].(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		pattern, err := strconv.Unquote(lit.Value)
		if err != nil {
			return true
		}
		method, path, found := strings.Cut(pattern, " ")
		if !found {
			method, path = "", pattern
		}
		r := routeDoc{Method: method, Path: path}
		if h, ok := call.Args[1].(*ast.SelectorExpr); ok {
			r.Handler = h.Sel.Name
		}
		out = append(out, r)
		return true
	})
	return out
}

func collectFields(st *ast.StructType) []fieldDoc {
	var out []fieldDoc
	for _, f := range st.Fields.List {
		var jsonName string
		var omitempty bool
		if f.Tag != nil {
			if tag, err := strconv.Unquote(f.Tag.Value); err == nil {
				v := reflect.StructTag(tag).Get("json")
				parts := strings.Split(v, ",")
				jsonName = parts[0]
				for _, p := range parts[1:] {
					if p == "omitempty" {
						omitempty = true
					}
				}
			}
		}
		if jsonName == "-" {
			continue
		}
		doc := ""
		if f.Doc != nil {
			doc = cleanDoc(f.Doc.Text())
		}
		goType := exprString(f.Type)
		if len(f.Names) == 0 { // embedded
			out = append(out, fieldDoc{GoName: goType, JSONName: jsonName, GoType: goType, Doc: doc, Omitempty: omitempty})
			continue
		}
		for _, n := range f.Names {
			if !n.IsExported() {
				continue
			}
			name := jsonName
			if name == "" {
				name = n.Name
			}
			out = append(out, fieldDoc{GoName: n.Name, JSONName: name, GoType: goType, Doc: doc, Omitempty: omitempty})
		}
	}
	return out
}

// exprString renders a type expression the way it was written. Enough for the
// shapes in this package; anything unrecognised falls back to its Go syntax
// rather than being dropped.
func exprString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	case *ast.ArrayType:
		return "[]" + exprString(t.Elt)
	case *ast.MapType:
		return "map[" + exprString(t.Key) + "]" + exprString(t.Value)
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.InterfaceType:
		return "any"
	default:
		return fmt.Sprintf("%T", e)
	}
}

// cleanDoc drops the leading "Name " that Go convention puts on a doc comment,
// so a field reads as prose under its own heading rather than repeating itself.
func cleanDoc(s string) string { return strings.TrimRight(s, "\n") }

// --- rendering --------------------------------------------------------------

func renderAPIDocs(pkg *packageDocs) (string, error) {
	var b strings.Builder

	b.WriteString("# HTTP API\n\n")
	b.WriteString("<!-- GENERATED FILE. Do not edit by hand.\n")
	b.WriteString("     Every word below comes from daemon/internal/boa: the routes from the mux\n")
	b.WriteString("     registrations in api.go, the prose from the Go doc comments on the handlers\n")
	b.WriteString("     and the wire types. Edit those and regenerate:\n\n")
	b.WriteString("         cd daemon && go test ./internal/boa/ -run TestAPIDocs -update\n\n")
	b.WriteString("     TestAPIDocsUpToDate fails if this file and the source disagree, so it\n")
	b.WriteString("     cannot go stale. -->\n\n")
	b.WriteString("The daemon serves this API on port 80 of the appliance and embeds the Vue\n")
	b.WriteString("interface behind it, so every endpoint here is same-origin with the UI.\n")
	b.WriteString("Units are the human-facing ones throughout -- megabits, milliseconds, percent;\n")
	b.WriteString("see `docs/DATA-CONTRACT.md` for where each number comes from.\n\n")

	// Endpoints, in registration order: api.go groups them meaningfully and
	// alphabetising would scatter each radio and device cluster.
	fmt.Fprintf(&b, "## Endpoints\n\n%d routes.\n\n", len(pkg.Routes))
	b.WriteString("| Method | Path |\n|---|---|\n")
	for _, r := range pkg.Routes {
		fmt.Fprintf(&b, "| %s | `%s` |\n", r.Method, r.Path)
	}
	b.WriteString("\n")

	for _, r := range pkg.Routes {
		fmt.Fprintf(&b, "### %s %s\n\n", r.Method, r.Path)
		if doc := pkg.HandlerDocs[r.Handler]; doc != "" {
			b.WriteString(doc + "\n\n")
		} else {
			b.WriteString("_No description: `" + r.Handler + "` has no doc comment._\n\n")
		}
	}

	b.WriteString("## Payload types\n\n")
	b.WriteString("The response shapes the interface consumes, and every type reachable from\n")
	b.WriteString("them. Field names are what appears on the wire.\n\n")

	for _, name := range reachableTypeNames() {
		td, ok := pkg.Types[name]
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "### %s", name)
		if ep := endpointFor(name); ep != "" {
			fmt.Fprintf(&b, " — %s", ep)
		}
		b.WriteString("\n\n")
		if td.Doc != "" {
			b.WriteString(td.Doc + "\n\n")
		}
		for _, f := range td.Fields {
			fmt.Fprintf(&b, "**`%s`** `%s`", f.JSONName, f.GoType)
			if f.Omitempty {
				b.WriteString(" _(omitted when empty)_")
			}
			b.WriteString("\n")
			if f.Doc != "" {
				b.WriteString(indent(f.Doc) + "\n")
			}
			b.WriteString("\n")
		}
	}
	return b.String(), nil
}

func indent(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if l != "" {
			lines[i] = "> " + l
		} else {
			lines[i] = ">"
		}
	}
	return strings.Join(lines, "\n")
}

// endpointFor names the route a root type is served by, for the ones that are.
func endpointFor(typeName string) string {
	for _, r := range wireRoots {
		if reflect.TypeOf(r.Value).Name() == typeName {
			return r.Endpoint
		}
	}
	return ""
}

// reachableTypeNames is every struct type reachable from a wire root, roots
// first and then their dependencies alphabetically, so the document opens with
// the shapes a reader is looking for.
func reachableTypeNames() []string {
	seen := map[string]bool{}
	var roots, rest []string

	var walk func(t reflect.Type, isRoot bool)
	walk = func(t reflect.Type, isRoot bool) {
		for t.Kind() == reflect.Ptr || t.Kind() == reflect.Slice || t.Kind() == reflect.Array || t.Kind() == reflect.Map {
			t = t.Elem()
		}
		if t.Kind() != reflect.Struct || t == reflect.TypeOf(time.Time{}) {
			return
		}
		name := t.Name()
		if name == "" || seen[name] {
			return
		}
		seen[name] = true
		if isRoot {
			roots = append(roots, name)
		} else {
			rest = append(rest, name)
		}
		for i := 0; i < t.NumField(); i++ {
			if t.Field(i).IsExported() {
				walk(t.Field(i).Type, false)
			}
		}
	}
	for _, r := range wireRoots {
		walk(reflect.TypeOf(r.Value), true)
	}
	sortStrings(rest)
	return append(roots, rest...)
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
