<script setup lang="ts">
/**
 * The pattern library: pick what this device plays.
 *
 * # Why the list is fetched rather than held here
 *
 * valley and pyramid are GENERATED by the daemon from this device's ladder,
 * every time they are listed. Their rates are the caps that were observed to
 * put this client on each rendition, so re-sweeping the device reshapes them.
 * A client-side copy would be a guess at numbers the box has measured, and
 * would go stale silently.
 *
 * # Why single-select
 *
 * A device plays one pattern. Rows are radios rather than checkboxes because
 * the alternative implies a queue the player does not have, and a control that
 * offers something the runtime cannot do is a lie with a tick in it.
 *
 * # Why selecting does not start playback
 *
 * Select fills the device's pattern slot; play starts it. Ticking a row must
 * not begin conditioning a device's traffic -- you choose first, look at what
 * you chose, then play.
 */
import { computed, ref, watch } from 'vue';
import type { Ladder, Pattern, PatternEntry } from '@/types';

const props = defineProps<{
  mac: string;
  rev: number;
  /** The device's ladders. Built-ins are generated from ONE of them, and
   *  which one is a real choice: a device can hold a ladder per service and
   *  they share nothing, so "the ladder" is only meaningful once named. */
  ladders: Ladder[];
  /** The pattern currently loaded on the device, if any. */
  current: Pattern | null;
  /** True while a run is in progress: the selection is what is playing, so
   *  changing it under a run would swap the timeline mid-flight. */
  locked: boolean;
}>();
const emit = defineEmits<{ changed: [] }>();

/*
 * Stretch stops, rather than a continuous 0-to-N slider.
 *
 * A continuous slider can reach 0, and 0 is not "unset" -- it collapses every
 * keyframe onto one instant, which is a constant rate rather than a pattern.
 * The daemon refuses it for that reason, so offering it here would be offering
 * a position whose only outcome is an error. Discrete stops also keep the
 * values exact, where a float slider drifts to 1.0000001 and shows it.
 *
 * The span is chosen from measurement: 1x is 30s a rung, enough to provoke a
 * player, and 2.5x is 75s, which is the dwell sweeps needed before a rendition
 * switch could be RELIED on. Both ends of that matter, so both are reachable.
 */
const STOPS = [0.25, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5];
const stopIdx = ref(STOPS.indexOf(1));
const stretch = computed(() => STOPS[stopIdx.value]);

/*
 * Empty means "let the daemon take the most recently measured", which is the
 * one the operator was last working on. Named explicitly as soon as there is
 * more than one to choose between.
 */
const service = ref('');
const rows = ref<PatternEntry[]>([]);
const error = ref('');
const loading = ref(false);
const saveName = ref('');
const saveErr = ref('');

async function load() {
  if (!props.mac) return;
  loading.value = true;
  try {
    const q = new URLSearchParams({
      mac: props.mac,
      stretch: String(stretch.value),
    });
    if (service.value) q.set('service', service.value);
    const r = await fetch(`/api/patterns?${q}`);
    if (!r.ok) {
      error.value = (await r.json()).error ?? `HTTP ${r.status}`;
      return;
    }
    rows.value = (await r.json()).patterns as PatternEntry[];
    error.value = '';
  } catch (e) {
    error.value = String(e);
  } finally {
    loading.value = false;
  }
}

/*
 * Re-listed when the stretch moves, because the durations shown ARE the
 * stretched ones -- the row is a preview of what selecting it would do.
 *
 * Debounced, for the reason useDevice documents: dragging a range input fires
 * an event per pixel, so an undebounced fetch would put a request in flight per
 * stop crossed and let them land out of order, painting durations for a stretch
 * the slider has already left.
 */
let listTimer: number | undefined;
watch(
  () => [props.mac, service.value, stretch.value].join('|'),
  () => {
    window.clearTimeout(listTimer);
    listTimer = window.setTimeout(() => void load(), 150);
  },
  { immediate: true },
);
// A sweep finishing rewrites the ladder, and the built-ins are derived from it.
watch(() => props.rev, () => void load());

/** The name of the pattern loaded on the device, for the radio's checked row. */
const currentName = computed(() =>
  (props.current?.name ?? '').trim().toLowerCase(),
);

/*
 * Whether the loaded timeline is a built-in, which cannot be written over.
 *
 * Saving is offered whenever a pattern is loaded, rather than only when one
 * looks edited. Detecting "edited" by comparing the loaded pattern against its
 * library row does not work: a row's duration is the PREVIEW at the current
 * stretch, so moving the slider made every pattern look modified when nothing
 * had been touched. A false "you have unsaved changes" is worse than no
 * detection at all -- it teaches the operator to ignore the one message that
 * should mean something.
 *
 * So the prompt states the rule instead of guessing at intent: a built-in is
 * derived from the ladder and reshapes itself when the device is re-swept, so
 * keeping a version of it means giving it a name of its own.
 */
const onBuiltin = computed(() =>
  rows.value.some((r) => r.builtin && r.name === currentName.value),
);

async function choose(name: string) {
  if (props.locked) return;
  error.value = '';
  const r = await fetch(`/api/devices/${props.mac}/pattern/select`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      base_revision: props.rev,
      name,
      service: service.value,
      // Always explicit, never 0: see STOPS.
      stretch: stretch.value,
    }),
  });
  if (!r.ok) {
    error.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  emit('changed');
  void load();
}

/**
 * Resolves the pattern being copied from.
 *
 * A built-in has no stored keyframes -- it is generated from the ladder on
 * demand -- so its rates have to be asked for. Read-only: it must not select
 * the pattern onto the device, because copying something is not choosing it.
 */
async function resolve(name: string): Promise<Pattern | null> {
  const q = new URLSearchParams({ mac: props.mac, stretch: String(stretch.value) });
  if (service.value) q.set('service', service.value);
  const r = await fetch(`/api/patterns/${encodeURIComponent(name)}?${q}`);
  if (!r.ok) {
    saveErr.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return null;
  }
  return (await r.json()).pattern as Pattern;
}

async function saveAs() {
  const name = saveName.value.trim();
  saveErr.value = '';
  if (!name) return;
  const src = cloneFrom.value
    ? await resolve(cloneFrom.value)
    : props.current;
  if (!src) return;
  const r = await fetch(`/api/patterns/${encodeURIComponent(name)}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ pattern: { ...src, name } }),
  });
  if (!r.ok) {
    // The daemon refuses built-in names, because a saved copy wearing the
    // label "valley" would make it mean different things on different boxes.
    // Its reason is better than anything this component could invent.
    saveErr.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  saveName.value = '';
  showSave.value = false;
  cloneFrom.value = '';
  await load();
  await choose(name);
}

/**
 * The merge selection, in the order it was built.
 *
 * Order is not decoration: where two sources drive the same axis the first
 * wins, so this array IS the precedence rule. It is a list rather than a Set
 * for exactly that reason.
 *
 * Alt-click rather than a checkbox column: merging is occasional, and a column
 * of empty boxes down every row would charge the common case -- picking one
 * pattern -- for the rare one.
 */
const merging = ref<string[]>([]);

function toggleMerge(name: string) {
  const i = merging.value.indexOf(name);
  if (i >= 0) merging.value.splice(i, 1);
  else merging.value.push(name);
}

/** 1-based position, or 0 when not selected. Shown on the row as its rank. */
const mergeRank = (name: string) => merging.value.indexOf(name) + 1;

function onRowClick(e: MouseEvent, name: string) {
  if (e.altKey) {
    toggleMerge(name);
    return;
  }
  void choose(name);
}

/**
 * Right-click merges when a selection is standing, and clones otherwise.
 *
 * One gesture doing two things, chosen by whether the operator has built a
 * selection -- which they can see, because the rows carry their rank. Adding a
 * second gesture for a second rare action would cost more than it saves.
 */
function onRowContext(r: PatternEntry) {
  if (merging.value.length >= 2) {
    void previewMerge();
    return;
  }
  startClone(r);
}

const mergePreview = ref<Pattern | null>(null);
const mergeErr = ref('');

/**
 * Merged on the box, not here.
 *
 * The daemon owns which value wins, how the lengths reconcile and whether the
 * result is even legal -- reorder over a zero delay is refused, and its message
 * says why better than this component could. Rebuilding any of that in the
 * browser would be a second implementation to keep true.
 */
async function previewMerge() {
  mergeErr.value = '';
  mergePreview.value = null;
  const r = await fetch('/api/patterns/merge', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      names: merging.value,
      mac: props.mac,
      service: service.value,
      stretch: stretch.value,
    }),
  });
  if (!r.ok) {
    mergeErr.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  mergePreview.value = (await r.json()).pattern as Pattern;
  saveName.value = merging.value.join('+');
}

async function saveMerge() {
  const name = saveName.value.trim();
  if (!name || !mergePreview.value) return;
  const r = await fetch(`/api/patterns/${encodeURIComponent(name)}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ pattern: { ...mergePreview.value, name } }),
  });
  if (!r.ok) {
    mergeErr.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  clearMerge();
  await load();
  await choose(name);
}

function clearMerge() {
  merging.value = [];
  mergePreview.value = null;
  mergeErr.value = '';
  saveName.value = '';
}

/** Steps and duration of the preview, phrased the way a row is. */
const mergeDetail = computed(() => {
  const p = mergePreview.value;
  if (!p?.keys?.length) return '';
  return `${p.keys.length} steps · ${fmtDur(p.keys[p.keys.length - 1].at_sec)}`;
});

async function remove(name: string) {
  const r = await fetch(`/api/patterns/${encodeURIComponent(name)}`, {
    method: 'DELETE',
  });
  if (!r.ok) {
    error.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  void load();
}

function fmtDur(sec: number) {
  if (sec < 60) return `${sec.toFixed(0)}s`;
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return s ? `${m}m${String(s).padStart(2, '0')}s` : `${m}m`;
}

/*
 * The selected row, which is the only one whose detail is worth showing.
 *
 * The per-row detail used to be repeated on every line, and for the built-ins
 * it was character-for-character identical -- same ladder, same step count,
 * same stretch. Six lines of chrome to say one thing twice. Only the selection
 * has context worth spending a line on.
 */
const sel = computed(() => rows.value.find((r) => r.name === currentName.value));

/** The save field is revealed on request: naming is rare, the picker is not. */
const showSave = ref(false);

/*
 * Which pattern a save will copy FROM.
 *
 * Empty means the timeline currently loaded on the device -- the plain
 * "save as..." case. Set by right-clicking a chip, which seeds the field from
 * that pattern instead, so a new one can be started from any pattern in the
 * list without first selecting it onto the device and disturbing what it is
 * set to.
 */
const cloneFrom = ref('');

/*
 * Right-click clones. It is the panel's existing idiom rather than a new one:
 * the timeline below already uses right-click to add a keyframe at a point and
 * to delete one.
 *
 * A clone is a SNAPSHOT. It takes the built-in's rates as they are now and
 * stops tracking the ladder, which is the whole reason to make one -- an edited
 * copy that silently reshaped itself on the next sweep would not be a copy of
 * anything. The name is seeded with a suffix rather than left blank, because
 * the one rule the operator has to satisfy is that it cannot be the built-in's
 * own name.
 */
function startClone(r: PatternEntry) {
  if (props.locked || r.unavailable) return;
  cloneFrom.value = r.name;
  saveName.value = `${r.name}-copy`;
  saveErr.value = '';
  showSave.value = true;
}

function cancelSave() {
  showSave.value = false;
  cloneFrom.value = '';
  saveName.value = '';
  saveErr.value = '';
}

/**
 * Which ladder a built-in was actually generated from.
 *
 * Named even when the service picker says "most recent", because that is a rule
 * and not a name: without this, taking the default hides which of the device's
 * ladders the rates came from -- and a measured ladder and a typed one are
 * different strengths of claim.
 */
function ladderOf(r: PatternEntry) {
  if (r.ladder === 'default') return '— no ladder yet, generic rungs';
  return `${r.ladder_service} ${r.ladder}`;
}

/** Seconds per step, which is only meaningful for the uniform generated ones. */
function perStep(r: PatternEntry) {
  return r.keys > 1 ? r.dur_sec / (r.keys - 1) : 0;
}

/**
 * The one-line description of the selected pattern.
 *
 * Provenance stays, because it is load-bearing: a pattern built from the
 * stand-in ladder is a plausible shape rather than a description of this
 * content, and that must not have to be inferred from the rates. The ladder it
 * came from is named here too, where the picker sits, so the two are read
 * together.
 */
function detail(r: PatternEntry) {
  if (r.unavailable) return r.unavailable;
  const bits: string[] = [];
  if (!r.builtin) bits.push('saved');
  bits.push(`${r.keys} steps`);
  bits.push(fmtDur(r.dur_sec));
  if (!r.loop) bits.push('once');
  return bits.join(' · ');
}
</script>

<template>
  <div class="lib">
    <!-- One row: the choice, and how long each step lasts. A segmented control
         rather than a stack of radios, matching the toolbar's groups -- these
         are exclusive choices and the shared border says so, in a fraction of
         the height. -->
    <div class="line">
      <div class="seg" role="group" aria-label="Pattern">
        <button
          class="seg-btn" :class="{ on: !current }" :disabled="locked"
          title="no pattern - a fixed cap tests steady state only"
          @click="choose('')"
        >none</button>
        <button
          v-for="r in rows" :key="r.name"
          class="seg-btn"
          :class="{ on: currentName === r.name, saved: !r.builtin, picked: mergeRank(r.name) > 0 }"
          :disabled="locked || !!r.unavailable"
          :title="r.unavailable || `${r.name} — alt-click to add to a merge, right-click to ${merging.length >= 2 ? 'merge the selection' : 'copy it'}`"
          @click="onRowClick($event, r.name)"
          @contextmenu.prevent="onRowContext(r)"
        >{{ r.name }}<sup v-if="mergeRank(r.name)" class="rank">{{ mergeRank(r.name) }}</sup></button>
      </div>

      <!-- Labelled in seconds a step, because that is the quantity being
           reasoned about; the multiplier follows so the two are never
           confused. The note about 75s is a tooltip rather than a line of its
           own -- worth knowing once, not worth a row forever. -->
      <label
        class="step"
        title="1x is 30s a rung, enough to provoke a player. 2.5x is 75s, the dwell a sweep needed before a rendition switch could be relied on."
      >
        <span class="lbl">step</span>
        <input
          type="range" min="0" :max="STOPS.length - 1" step="1"
          :value="stopIdx" :disabled="locked"
          @input="stopIdx = +($event.target as HTMLInputElement).value"
        />
        <span class="val">{{ (30 * stretch).toFixed(0) }}s</span>
        <span class="mul">{{ stretch }}x</span>
      </label>

      <span class="spacer"></span>
      <button
        v-if="current && !showSave" class="ghost"
        title="keep this timeline in the library under a name"
        @click="showSave = true"
      >save as...</button>
    </div>

    <!-- One line of context for the SELECTION only. The ladder picker lives
         here, beside the provenance it explains, and only when the device has
         more than one ladder to choose between. -->
    <p class="det" :class="{ busy: loading }">
      <template v-if="sel">
        <span class="prov">{{ sel.builtin ? 'built-in from' : 'saved' }}</span>
        <!-- The picker sits beside the provenance it explains. "most recent" is
             a rule rather than a name, so the ladder it resolved to is printed
             after it -- otherwise choosing the default hides which of the
             device's ladders the rates actually came from. -->
        <select
          v-if="sel.builtin && ladders.length > 1"
          v-model="service" class="svc" :disabled="locked" aria-label="ladder"
        >
          <option value="">most recent</option>
          <option v-for="l in ladders" :key="l.service" :value="l.service">
            {{ l.service }}
          </option>
        </select>
        <span v-if="sel.builtin" class="prov">{{ ladderOf(sel) }}</span>
        <span class="prov">· {{ detail(sel) }}</span>
        <button
          v-if="!sel.builtin" class="ghost x" title="delete this saved pattern"
          @click="remove(sel.name)"
        >delete</button>
      </template>
      <template v-else-if="current">
        <span class="prov">{{ current.name }} — not in the library</span>
      </template>
      <template v-else>
        <span class="prov">a fixed cap — tests steady state only</span>
      </template>
    </p>

    <!-- The merge bar. Present only while a selection stands, because it is
         the only time it says anything, and it states the ORDER because that
         order is the rule: first to drive an axis owns it. -->
    <div v-if="merging.length" class="merge">
      <span class="meta">merge</span>
      <span class="chain">
        <template v-for="(n, i) in merging" :key="n">
          <span v-if="i" class="plus">+</span>
          <span class="src">{{ n }}</span>
        </template>
      </span>
      <span v-if="merging.length < 2" class="meta">alt-click one more</span>
      <template v-else-if="!mergePreview">
        <button @click="previewMerge()">merge</button>
        <span class="meta">first to set a field wins it</span>
      </template>
      <template v-else>
        <span class="meta num">{{ mergeDetail }}</span>
        <input
          v-model="saveName" placeholder="name the merged pattern"
          @keyup.enter="saveMerge()" @keyup.esc="clearMerge()"
        />
        <button :disabled="!saveName.trim()" @click="saveMerge()">save</button>
      </template>
      <button class="ghost" @click="clearMerge()">clear</button>
      <span v-if="mergeErr" class="err">{{ mergeErr }}</span>
    </div>

    <div v-if="showSave" class="saveas">
      <span class="meta">{{ cloneFrom ? `copy of ${cloneFrom}` : 'save this timeline' }}</span>
      <input
        v-model="saveName" placeholder="name this pattern"
        @keyup.enter="saveAs()" @keyup.esc="cancelSave()"
      />
      <button :disabled="!saveName.trim()" @click="saveAs()">save</button>
      <button class="ghost" @click="cancelSave()">cancel</button>
      <span v-if="!cloneFrom && sel?.builtin" class="meta">
        a built-in needs a name of its own
      </span>
    </div>
    <p v-if="saveErr" class="err">{{ saveErr }}</p>
    <p v-if="error" class="err">{{ error }}</p>
  </div>
</template>

<style scoped>
/* A picked row keeps its own outline rather than borrowing the selected
   state's: being in a merge and being the running pattern are different facts,
   and a row can be both. */
.seg-btn.picked { box-shadow: inset 0 0 0 2px var(--accent, #5b8def); }
.rank {
  font-size: 9px; margin-left: 3px; opacity: 0.85;
  font-variant-numeric: tabular-nums;
}
.merge {
  display: flex; align-items: center; gap: 8px; flex-wrap: wrap;
  margin-top: 8px; padding: 6px 8px;
  border: 1px solid var(--line); border-radius: 6px;
}
.merge .chain { display: flex; align-items: center; gap: 6px; }
.merge .src {
  font-size: 12px; padding: 1px 6px;
  border: 1px solid var(--line); border-radius: 4px;
}
.merge .plus { color: var(--ink-faint); font-size: 11px; }
.merge input { min-width: 180px; }
.merge .err { color: var(--bad, #d66); font-size: 12px; }

.lib { display: flex; flex-direction: column; gap: 4px; }
.line { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.spacer { flex: 1; }

/* Matches the chart toolbar: exclusive choices sharing one border. */
.seg { display: flex; border: 1px solid var(--line); border-radius: 6px; overflow: hidden; }
.seg-btn {
  padding: 3px 10px;
  font: inherit; font-size: 12px;
  color: var(--ink-dim);
  background: var(--panel-2);
  border: 0; border-left: 1px solid var(--line);
  cursor: pointer;
}
.seg-btn:first-child { border-left: 0; }
.seg-btn:hover:not(:disabled) { color: var(--ink); background: var(--line); }
.seg-btn.on { color: var(--ink); background: var(--line); font-weight: 600; }
.seg-btn:disabled { opacity: 0.45; cursor: default; }
.seg-btn:focus-visible { outline: 2px solid var(--down); outline-offset: -2px; }
/* Saved patterns are the operator's own, so they read differently from the two
   the box generates. */
.seg-btn.saved { font-style: italic; }

.step { display: flex; align-items: center; gap: 6px; font-size: 12px; }
.step input[type='range'] { width: 110px; }
.lbl {
  font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase;
  color: var(--ink-faint);
}
.val { font-variant-numeric: tabular-nums; color: var(--ink); }
.mul { color: var(--ink-faint); }

.det {
  margin: 0; font-size: 12px; color: var(--ink-dim);
  display: flex; align-items: baseline; gap: 4px; flex-wrap: wrap;
}
/* Dimmed rather than blanked while re-listing, so moving the slider reads as
   the numbers changing rather than the line disappearing and coming back. */
.det.busy { opacity: 0.55; }
.prov { color: var(--ink-faint); }
.svc {
  font: inherit; font-size: 12px; padding: 0 2px;
  color: var(--ink-dim); background: transparent;
  border: 0; border-bottom: 1px dotted var(--line); cursor: pointer;
}
.x { margin-left: 8px; }

.saveas { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
.saveas input { flex: 0 1 14em; }
.err { color: var(--bad, #c0392b); margin: 0; font-size: 12px; }
.meta { color: var(--ink-faint); font-size: 12px; }
</style>