<script setup lang="ts">
/**
 * The pattern library: pick what this device plays.
 *
 * # Why the list is fetched rather than held here
 *
 * valley and pyramid are GENERATED by the daemon from this device's ladder,
 * every time they are listed. Their rates are the caps that were observed to
 * put this client on each rendition, so re-sweeping the device reshapes them.
 * A client-side copy would be a guess at numbers the box has measured, and
 * would go stale silently.
 *
 * # Why single-select
 *
 * A device plays one pattern. Rows are radios rather than checkboxes because
 * the alternative implies a queue the player does not have, and a control that
 * offers something the runtime cannot do is a lie with a tick in it.
 *
 * # Why selecting does not start playback
 *
 * Select fills the device's pattern slot; play starts it. Ticking a row must
 * not begin conditioning a device's traffic -- you choose first, look at what
 * you chose, then play.
 */
import { computed, ref, watch } from 'vue';
import type { Ladder, Pattern, PatternEntry } from '@/types';

const props = defineProps<{
  mac: string;
  rev: number;
  /** The device's ladders. Built-ins are generated from ONE of them, and
   *  which one is a real choice: a device can hold a ladder per service and
   *  they share nothing, so "the ladder" is only meaningful once named. */
  ladders: Ladder[];
  /** The pattern currently loaded on the device, if any. */
  current: Pattern | null;
  /** True while a run is in progress: the selection is what is playing, so
   *  changing it under a run would swap the timeline mid-flight. */
  locked: boolean;
}>();
const emit = defineEmits<{ changed: [] }>();

/*
 * Stretch stops, rather than a continuous 0-to-N slider.
 *
 * A continuous slider can reach 0, and 0 is not "unset" -- it collapses every
 * keyframe onto one instant, which is a constant rate rather than a pattern.
 * The daemon refuses it for that reason, so offering it here would be offering
 * a position whose only outcome is an error. Discrete stops also keep the
 * values exact, where a float slider drifts to 1.0000001 and shows it.
 *
 * The span is chosen from measurement: 1x is 30s a rung, enough to provoke a
 * player, and 2.5x is 75s, which is the dwell sweeps needed before a rendition
 * switch could be RELIED on. Both ends of that matter, so both are reachable.
 */
const STOPS = [0.25, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5];
const stopIdx = ref(STOPS.indexOf(1));
const stretch = computed(() => STOPS[stopIdx.value]);

/*
 * Empty means "let the daemon take the most recently measured", which is the
 * one the operator was last working on. Named explicitly as soon as there is
 * more than one to choose between.
 */
const service = ref('');
const rows = ref<PatternEntry[]>([]);
const error = ref('');
const loading = ref(false);
const saveName = ref('');
const saveErr = ref('');

async function load() {
  if (!props.mac) return;
  loading.value = true;
  try {
    const q = new URLSearchParams({
      mac: props.mac,
      stretch: String(stretch.value),
    });
    if (service.value) q.set('service', service.value);
    const r = await fetch(`/api/patterns?${q}`);
    if (!r.ok) {
      error.value = (await r.json()).error ?? `HTTP ${r.status}`;
      return;
    }
    rows.value = (await r.json()).patterns as PatternEntry[];
    error.value = '';
  } catch (e) {
    error.value = String(e);
  } finally {
    loading.value = false;
  }
}

/*
 * Re-listed when the stretch moves, because the durations shown ARE the
 * stretched ones -- the row is a preview of what selecting it would do.
 *
 * Debounced, for the reason useDevice documents: dragging a range input fires
 * an event per pixel, so an undebounced fetch would put a request in flight per
 * stop crossed and let them land out of order, painting durations for a stretch
 * the slider has already left.
 */
let listTimer: number | undefined;
watch(
  () => [props.mac, service.value, stretch.value].join('|'),
  () => {
    window.clearTimeout(listTimer);
    listTimer = window.setTimeout(() => void load(), 150);
  },
  { immediate: true },
);
// A sweep finishing rewrites the ladder, and the built-ins are derived from it.
watch(() => props.rev, () => void load());

/** The name of the pattern loaded on the device, for the radio's checked row. */
const currentName = computed(() =>
  (props.current?.name ?? '').trim().toLowerCase(),
);

/*
 * Whether the loaded timeline is a built-in, which cannot be written over.
 *
 * Saving is offered whenever a pattern is loaded, rather than only when one
 * looks edited. Detecting "edited" by comparing the loaded pattern against its
 * library row does not work: a row's duration is the PREVIEW at the current
 * stretch, so moving the slider made every pattern look modified when nothing
 * had been touched. A false "you have unsaved changes" is worse than no
 * detection at all -- it teaches the operator to ignore the one message that
 * should mean something.
 *
 * So the prompt states the rule instead of guessing at intent: a built-in is
 * derived from the ladder and reshapes itself when the device is re-swept, so
 * keeping a version of it means giving it a name of its own.
 */
const onBuiltin = computed(() =>
  rows.value.some((r) => r.builtin && r.name === currentName.value),
);

async function choose(name: string) {
  if (props.locked) return;
  error.value = '';
  const r = await fetch(`/api/devices/${props.mac}/pattern/select`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      base_revision: props.rev,
      name,
      service: service.value,
      // Always explicit, never 0: see STOPS.
      stretch: stretch.value,
    }),
  });
  if (!r.ok) {
    error.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  emit('changed');
  void load();
}

async function saveAs() {
  const name = saveName.value.trim();
  saveErr.value = '';
  if (!name || !props.current) return;
  const r = await fetch(`/api/patterns/${encodeURIComponent(name)}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ pattern: { ...props.current, name } }),
  });
  if (!r.ok) {
    // The daemon refuses built-in names, because a saved copy wearing the
    // label "valley" would make it mean different things on different boxes.
    // Its reason is better than anything this component could invent.
    saveErr.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  saveName.value = '';
  await load();
  await choose(name);
}

async function remove(name: string) {
  const r = await fetch(`/api/patterns/${encodeURIComponent(name)}`, {
    method: 'DELETE',
  });
  if (!r.ok) {
    error.value = (await r.json()).error ?? `HTTP ${r.status}`;
    return;
  }
  void load();
}

function fmtDur(sec: number) {
  if (sec < 60) return `${sec.toFixed(0)}s`;
  const m = Math.floor(sec / 60);
  const s = Math.round(sec % 60);
  return s ? `${m}m${String(s).padStart(2, '0')}s` : `${m}m`;
}

/** Seconds per step, which is only meaningful for the uniform generated ones. */
function perStep(r: PatternEntry) {
  return r.keys > 1 ? r.dur_sec / (r.keys - 1) : 0;
}

function detail(r: PatternEntry) {
  if (r.unavailable) return r.unavailable;
  const bits: string[] = [];
  if (r.builtin) {
    // Provenance is load-bearing: a pattern built from the stand-in ladder is
    // a plausible shape, not a description of this content.
    bits.push(
      r.ladder === 'default'
        ? 'built-in · no ladder yet, generic rungs'
        : `built-in · ${r.ladder_service} ${r.ladder}`,
    );
  } else {
    bits.push('saved');
  }
  bits.push(`${r.keys} steps`);
  if (r.builtin) bits.push(`${perStep(r).toFixed(0)}s each`);
  bits.push(fmtDur(r.dur_sec));
  return bits.join(' · ');
}
</script>

<template>
  <div class="lib">
    <!-- Which ladder the generated patterns describe. Only shown when there is
         a choice: one ladder needs no picker, and the row detail already names
         whichever was used. -->
    <div v-if="ladders.length > 1" class="svc">
      <label :for="`svc-${mac}`">ladder</label>
      <select :id="`svc-${mac}`" v-model="service" :disabled="locked">
        <option value="">most recent</option>
        <option v-for="l in ladders" :key="l.service" :value="l.service">
          {{ l.service }} — {{ l.rungs.length }} rungs, {{ l.provenance }}
        </option>
      </select>
    </div>

    <div class="rows" :class="{ busy: loading }">
      <!-- "none" is a real choice, not an empty state: a fixed cap is a
           legitimate test, and clearing the pattern is how you get back to it. -->
      <label class="row" :class="{ dim: locked }">
        <input
          type="radio" :name="`pat-${mac}`" :checked="!current"
          :disabled="locked" @change="choose('')"
        />
        <span class="nm">none</span>
        <span class="det">a fixed cap — tests steady state only</span>
      </label>

      <label
        v-for="r in rows" :key="r.name" class="row"
        :class="{ dim: locked || !!r.unavailable, bad: !!r.unavailable }"
      >
        <input
          type="radio" :name="`pat-${mac}`"
          :checked="currentName === r.name"
          :disabled="locked || !!r.unavailable"
          @change="choose(r.name)"
        />
        <span class="nm">{{ r.name }}</span>
        <span class="det">{{ detail(r) }}</span>
        <button
          v-if="!r.builtin" class="ghost x" title="delete this saved pattern"
          @click.prevent="remove(r.name)"
        >×</button>
      </label>
    </div>

    <!-- The stretch applies to whichever row is selected next, so it sits with
         the list rather than inside the editor. Labelled in seconds a step,
         because that is the quantity being reasoned about; the multiplier is
         shown too so the two are never confused. -->
    <div class="stretch">
      <label :for="`st-${mac}`">step</label>
      <input
        :id="`st-${mac}`" type="range" min="0" :max="STOPS.length - 1" step="1"
        :value="stopIdx" :disabled="locked"
        @input="stopIdx = +($event.target as HTMLInputElement).value"
      />
      <span class="val">
        {{ (30 * stretch).toFixed(0) }}s <span class="mul">({{ stretch }}×)</span>
      </span>
    </div>
    <p v-if="stretch === 2.5" class="meta hint">
      75s a rung is the dwell a sweep needed before a switch could be relied on.
    </p>

    <!-- Keeping a timeline means naming it. A built-in cannot be written over:
         it is derived, and a frozen copy under its name would mean something
         different here than everywhere else. -->
    <div v-if="current" class="saveas">
      <span class="meta">
        {{
          onBuiltin
            ? 'built-in — edits need a name of their own'
            : 'save this timeline to the library'
        }}
      </span>
      <input
        v-model="saveName" placeholder="name this pattern"
        @keyup.enter="saveAs()"
      />
      <button :disabled="!saveName.trim()" @click="saveAs()">save as</button>
    </div>
    <p v-if="saveErr" class="err">{{ saveErr }}</p>
    <p v-if="error" class="err">{{ error }}</p>
    <p v-if="locked" class="meta">stop the run to change pattern</p>
  </div>
</template>

<style scoped>
.lib { display: flex; flex-direction: column; gap: 6px; }
.svc { display: flex; align-items: center; gap: 8px; }
.rows { display: flex; flex-direction: column; gap: 2px; }
/* Dimmed rather than blanked while re-listing: the previous durations stay
   readable, so moving the slider reads as the numbers changing rather than as
   the list disappearing and coming back. */
.rows.busy { opacity: 0.6; }
.row {
  display: flex; align-items: baseline; gap: 8px;
  padding: 3px 4px; border-radius: 4px; cursor: pointer;
}
.row:hover { background: var(--row-hover, rgba(127, 127, 127, 0.12)); }
.row.dim { opacity: 0.5; cursor: default; }
.row.bad .det { font-style: italic; }
.nm { min-width: 8.5em; font-weight: 600; }
.det { color: var(--muted, #888); font-size: 0.85em; }
.x { margin-left: auto; opacity: 0.5; }
.x:hover { opacity: 1; }
.stretch { display: flex; align-items: center; gap: 8px; }
.stretch input[type='range'] { flex: 1; max-width: 220px; }
.stretch .val { font-variant-numeric: tabular-nums; }
.mul { color: var(--muted, #888); }
.hint { margin: 0; }
.saveas { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.saveas input { flex: 1; min-width: 10em; }
.err { color: var(--bad, #c0392b); margin: 2px 0 0; font-size: 0.85em; }
.meta { color: var(--muted, #888); font-size: 0.85em; margin: 0; }
</style>
